// import "./css/style.css";
// import { SessionProvider } from "next-auth/react";
// import { Inter } from "next/font/google";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <body
//         className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
//       >
//         <SessionProvider>
//         <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
//           {children}
//         </div>
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import DefaultLayout from "./default";
import "./css/style.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
      className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}