import "./css/style.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// export const metadata = {
//   title: "BlueHouse Technologies",
//   // description: "Generated by create next app",
//   icons: {
//     icon: '/bluehouse-logo.png',
//     apple: '/bluehouse-logo.png', sizes: '192x192',
//   },
// };
export const metadata = {
  title: "Bluehouse Technologies",
  icons: {
    icon: [
      { url: '/bluehouse-logo.png', sizes: '32x32', type: 'image/png' },
      { url: '/bluehouse-logo-large.png', sizes: '192x192', type: 'image/png' },
    ],
    apple: [
      { url: '/bluehouse-logo.png', sizes: '180x180', type: 'image/png' },
    ],
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
      </body>
    </html>
  );
}
